name: CI/CD

on:
  push:
    tags:
      - 'app'
env:
  GITHUB_SHA: ${{github.sha}}
  GITHUB_REF: ${{github.ref}}
  IMAGE: monorepo
  REGISTRY_HOSTNAME: gcr.io
  IMAGE_NAME: monorepo-helloworld
  PROJECT_NAME: ${{ secrets.GCR_PROJECT_ID }}
  GCR_KEY: ${{ secrets.GCR_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0

      - uses: nrwl/nx-set-shas@v3
      - name: Install dependencies
        run: npm ci

      - name: Run affected tests
        run: npx nx affected:test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Environment variables available to all jobs and steps in this workflow

      # Setup gcloud CLI
      - name: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${GCR_KEY}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: 'Use gcloud CLI'
        run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker
      # Build the Docker image
      - name: 'Build'
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker build -t "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE_NAME":"$TAG" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
      # Push the Docker image to Google Container Registry
      - name: 'Publish'
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker push "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE_NAME":"$TAG"
          docker tag "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE_NAME":"$TAG" "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE_NAME":latest-"$TAG"
          docker push "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE_NAME":latest-"$TAG"

      # - name: Build and push Docker image
      #   if: success()
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: gcr.io/${GCR_PROJECT_ID}/mono-app
      #   env:
      #     GCR_PROJECT_ID: ${{ secrets.GCR_PROJECT_ID }}
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Deploy to GKE
      #   if: success()
      #   uses: GoogleCloudPlatform/github-actions/gke-deploy
      #   with:
      #     cluster-name: monorepo-testing-001
      #     service-name: my-service
      #     image-url: gcr.io/${GCR_PROJECT_ID}/mono-app
      #     namespace: default
      #     wait-for-rollout: true
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      #     CLOUDSDK_COMPUTE_ZONE: asia-east1-a
      #     CLOUDSDK_CORE_PROJECT: ${GCR_PROJECT_ID}
