name: CI/CD

on:
  push:
    tags:
      - 'app'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0

      - uses: nrwl/nx-set-shas@v3
      - name: Install dependencies
        run: npm ci

      - name: Run affected tests
        run: npx nx affected:test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Building and pushing the image
        # uses: ./
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta # <- use this on your workflow
        with:
          gcloud_service_key: ${ secrets.GOOGLE_APPLICATION_CREDENTIALS } # <- not needed when used with google-github-actions/auth@v0
          registry: gcr.io
          project_id: ${ secrets.GCR_PROJECT_ID }
          image_name: mono-test
          image_tag: monorepo
          dockerfile: ./
          context: ./
          target: build

      # - name: Build and push Docker image
      #   if: success()
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: gcr.io/${GCR_PROJECT_ID}/mono-app
      #   env:
      #     GCR_PROJECT_ID: ${{ secrets.GCR_PROJECT_ID }}
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Deploy to GKE
      #   if: success()
      #   uses: GoogleCloudPlatform/github-actions/gke-deploy
      #   with:
      #     cluster-name: monorepo-testing-001
      #     service-name: my-service
      #     image-url: gcr.io/${GCR_PROJECT_ID}/mono-app
      #     namespace: default
      #     wait-for-rollout: true
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      #     CLOUDSDK_COMPUTE_ZONE: asia-east1-a
      #     CLOUDSDK_CORE_PROJECT: ${GCR_PROJECT_ID}
