name: CI/CD

on:
  push:
    tags:
      - 'app'

stages:
  - build
  - deploy

env:
  GITHUB_SHA: ${{github.sha}}
  GITHUB_REF: ${{github.ref}}
  IMAGE: 'node:16.15.0'
  REGISTRY_HOSTNAME: 'gcr.io'
  IMAGE_NAME: 'monorepoo'
  PROJECT_NAME: ${{secrets.GCR_PROJECT_ID}}
  CLUSTER_NAME: 'monorepo-testing-001'
  ZONE: 'asia-east1'
  CONTAINER_NAME: 'k8s-container'
  DEPLOYMENT_NAME: 'k8s-deployment'

jobs:
  setup-build-publish-deploy:
    stage: build
    name: 'Setup, Build, and Publish'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      # Setup gcloud CLI
      - name: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{secrets.GCR_KEY}}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: 'Use gcloud CLI'
        run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker
      # Build the Docker image
      - name: 'Build'
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker build -t "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE_NAME":"$TAG" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
      # Push the Docker image to Google Container Registry
      - name: 'Publish'
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker push "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE_NAME":"$TAG"
          docker tag "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE_NAME":"$TAG" "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE_NAME":latest-"$TAG"
          docker push "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE_NAME":latest-"$TAG"

      - name: 'deploy to GKE'
        script:
          - echo "$GCLOUD_SERVICE_KEY" | base64 --decode -i > service-key.json
          - gcloud auth activate-service-account --key-file service-key.json
          - gcloud config set project ${{secrets.GCR_PROJECT_ID}}
          - gcloud config set compute/zone ${ZONE}
          - gcloud container clusters get-credentials ${CLUSTER_NAME}
          - kubectl config set-context gke_${{secrets.GCR_PROJECT_ID}}_${ZONE}_${CLUSTER_NAME}
          - kubectl config use-context gke_${{secrets.GCR_PROJECT_ID}}_${ZONE}_${CLUSTER_NAME}
          - kubectl set image deployment/${DEPLOYMENT_NAME} ${CONTAINER_NAME}=gcr.io/${{secrets.GCR_PROJECT_ID}}/${IMAGE_NAME}:$CI_COMMIT_SHA
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 16.15.0

#       - uses: nrwl/nx-set-shas@v3
#       - name: Install dependencies
#         run: npm ci

#       - name: Run affected tests
#         run: npx nx affected:test
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       # - name: Build and push
#       #   uses: docker/build-push-action@v4
#       #   with:
#       #     push: true
#       #     tags: gcr.io/${{ secrets.GCR_PROJECT_ID }}/mono-app
#       - uses: Industrial/push-docker-gcr@latest
#         with:
#           docker_image_name: monorepo
#           docker_image_tag: latest
#           docker_context: .
#           gcr_host: gcr.io
#           gcr_project_id: ${{ secrets.GCR_PROJECT_ID }}
#           gcr_service_key: ${{ secrets.GCR_KEY }}

#       # - name: Set up Docker Buildx
#       #   uses: docker/setup-buildx-action@v2

#       # - name: Build and push Docker image
#       #   if: success()
#       #   uses: docker/build-push-action@v2
#       #   with:
#       #     context: .
#       #     push: true
#       #     tags: gcr.io/${GCR_PROJECT_ID}/mono-app
#       #     username: ${DOCKER_USERNAME }
#       #     password: ${DOCKER_PASSWORD }
#       #   env:
#       #     GCR_PROJECT_ID: ${{ secrets.GCR_PROJECT_ID }}
#       #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#       #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

#       # - name: Deploy to GKE
#       #   if: success()
#       #   uses: GoogleCloudPlatform/github-actions/gke-deploy
#       #   with:
#       #     cluster-name: monorepo-testing-001
#       #     service-name: my-service
#       #     image-url: gcr.io/${GCR_PROJECT_ID}/mono-app
#       #     namespace: default
#       #     wait-for-rollout: true
#       #   env:
#       #     GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#       #     CLOUDSDK_COMPUTE_ZONE: asia-east1-a
#       #     CLOUDSDK_CORE_PROJECT: ${GCR_PROJECT_ID}
